structure(list(method = "GET", url = "https://read-api.test/api/v1/requests/999999", 
    status_code = 404L, headers = structure(list(server = "nginx/1.25.4", 
        `content-type` = "application/json", vary = "Accept-Encoding", 
        `x-powered-by` = "PHP/8.5.8", `cache-control` = "no-cache, private", 
        date = "Wed, 26 Aug 2026 23:03:54 GMT", `x-ratelimit-limit` = "120", 
        `x-ratelimit-remaining` = "95", `access-control-allow-origin` = "*", 
        `content-encoding` = "gzip"), class = "httr2_headers"), 
    body = charToRaw("{\"message\":\"Not found.\"}"), timing = c(redirect = 0, 
    namelookup = 0, connect = 0, pretransfer = 6.2e-05, starttransfer = 0.157912, 
    total = 0.157965), cache = new.env(parent = emptyenv())), class = "httr2_response")
